Installing Load balancer

diff --git a/0x0F-load_balancer/1-install_load_balancer b/0x0F-load_balancer/1-install_load_balancer
--- a/0x0F-load_balancer/1-install_load_balancer
+++ b/0x0F-load_balancer/1-install_load_balancer
@@ -14,10 +14,10 @@ frontend  rufai5-frontend
         bind *:80
         mode http
         default_backend rufai5-backend
-backend joshua-backend
+backend rufai5-backend
         balance roundrobin
-        server 180682-web-01 54.160.65.96:80 check
-        server 180682-web-02 100.25.160.244:80 check
+        server 180682-web-01 54.175.191.156:80 check
+        server 180682-web-02 54.162.44.239:80 check
 "
 echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg
 
@@ -26,3 +26,11 @@ echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg
 echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
 
 sudo service haproxy restart
+
+# Test HAProxy configuration
+curl -s http://localhost:80/ | grep -q "Hello World!"
+if [ $? -eq 0 ]; then
+    echo "HAProxy installed and configured successfully!"
+else
+    echo "HAProxy configuration failed!"
+fi
